export const portfolio = {
  name: "Yousef Walid",
  monogram: "YW",
  role: "Software Engineer(Back-End .NET )",
  tagline: ".NET ",
  location: "Cairo, Egypt",
  phone: "+201006208930",
  email: "yousefwalid950@gmail.com",
  github: { user: "YousefWalid13", url: "https://github.com/YousefWalid13" },
  linkedin: { user: "Yousef Walid", url: "https://www.linkedin.com/in/yousefwalidsoftware" },
  about: [
    "Software Engineer specializing in ASP.NET Core and React, focused on building modern, scalable web applications with clean architecture and high-performance APIs.",
    "Passionate about designing maintainable backend systems, RESTful APIs, real-time applications, and delivering production-ready software using modern development practices.",
    "Graduated with a B.Sc. in Computer Science from Menoufia University (June 2026). Continuously learning new technologies and building end-to-end software solutions.",
  ],
  stack: [
    { name: "C#", slug: "csharp", url: "https://learn.microsoft.com/dotnet/csharp/" },
    { name: ".NET", slug: "dotnet", url: "https://dotnet.microsoft.com/" },
    { name: "TypeScript", slug: "typescript", url: "https://www.typescriptlang.org/" },
    {
      name: "JavaScript",
      slug: "javascript",
      url: "https://developer.mozilla.org/docs/Web/JavaScript",
    },
    { name: "Next.js", slug: "nextjs", url: "https://nextjs.org/" },
    { name: "Bun", slug: "bun", url: "https://bun.sh/" },
    { name: "tRPC", slug: "trpc", url: "https://trpc.io/" },
    { name: "Prisma", slug: "prisma", url: "https://www.prisma.io/" },
    { name: "Python", slug: "python", url: "https://www.python.org/" },
    { name: "Java", slug: "openjdk", url: "https://openjdk.org/" },
    { name: "React", slug: "react", url: "https://react.dev/" },
    { name: "Angular", slug: "angular", url: "https://angular.dev/" },
    { name: "Tailwind CSS", slug: "tailwindcss", url: "https://tailwindcss.com/" },
    { name: "Bootstrap", slug: "bootstrap", url: "https://getbootstrap.com/" },
    { name: "HTML5", slug: "html5", url: "https://developer.mozilla.org/docs/Web/HTML" },
    { name: "CSS3", slug: "css3", url: "https://developer.mozilla.org/docs/Web/CSS" },
    { name: "ASP.NET", slug: "dotnet", url: "https://dotnet.microsoft.com/apps/aspnet" },
    { name: "Entity Framework", slug: "nuget", url: "https://learn.microsoft.com/ef/" },
    { name: "SignalR", slug: "dotnet", url: "https://dotnet.microsoft.com/apps/aspnet/signalr" },
    { name: "SQL Server", slug: "microsoftsqlserver", url: "https://www.microsoft.com/sql-server" },
    { name: "PostgreSQL", slug: "postgresql", url: "https://www.postgresql.org/" },
    { name: "MongoDB", slug: "mongodb", url: "https://www.mongodb.com/" },
    { name: "Docker", slug: "docker", url: "https://www.docker.com/" },
    { name: "Git", slug: "git", url: "https://git-scm.com/" },
    { name: "GitHub", slug: "github", url: "https://github.com/" },
    { name: "JWT", slug: "jsonwebtokens", url: "https://jwt.io/" },
  ],
  projects: [
    {
      title: "Vibe — AI Website Builder (Graduation Project)",
      role: "Full-Stack Developer",

      description:
        "Graduation project focused on building an AI-powered website builder that generates, customizes, and deploys modern web applications from natural language prompts. Features AI-driven code generation, real-time editing, authentication, project management, and automated deployment workflows.",

      tags: [
        "Next.js",
        "React",
        "TypeScript",
        "tRPC",
        "Prisma",
        "PostgreSQL",
        "Inngest",
        "AI",
        "Tailwind CSS",
      ],
      github: "https://github.com/mohammedattia11/vibe.git",
      live: "https://vibe-presentation-one.vercel.app/",
      cover: "src/assets/vibe.png",
      video: "",
    },
    {
      title: "Fas7ny — Travel Planning Backend",
      role: "Back-End .NET Developer",
      description:
        "Full-featured backend built on Clean Architecture with booking workflows, Hangfire background jobs, Gemini-powered travel package generation, and JWT authentication.",
      tags: [
        "ASP.NET Core (.NET 9)",
        "EF Core",
        "MSSQL",
        "Hangfire",
        "JWT",
        "Clean Architecture",
        "AI (Gemini)",
        "Serilog",
      ],
      github: "https://github.com/Fas7ny/Fas7nyProject",
      cover: "src/assets/Fas7ny.png",
      video: "",
    },
    {
      title: "Vion — Real-Time Chat Platform",
      role: "Full-Stack Developer",
      description:
        "Real-time chat platform with SignalR WebSockets, room lifecycle management, typing indicators, and online presence. PostgreSQL on Neon, deployed to Fly.io and Vercel.",
      tags: ["ASP.NET Core (.NET 10)", "SignalR", "React", "PostgreSQL", "JWT", "Fly.io", "Vercel"],
      github: "https://github.com/YousefWalid13/Real-Time-Chat-App",
      live: "https://real-time-chat-app-sigma-ten.vercel.app/",
      cover: "src/assets/vion.png",
      video: "src/assets/vion_smol.mp4",
    },
  ],

  experience: [
    {
      company: "Commercial International Bank (CIB)",
      title: "CIB Training",
      period: "August 2025",
      hours: "120 hours",
      description:
        "Enhanced business analysis and communication through real-world financial case studies; sharpened teamwork and problem-solving across business and technical perspectives.",
      tags: ["Business Analysis", "Communication", "Teamwork", "Problem Solving"],
    },
    {
      company: "ITI",
      title: "Front-End Angular Training",
      period: "Jul — Aug 2025",
      hours: "120 hours",
      description:
        "Advanced Angular: component-based design, routing, form validation, and API integration. Built responsive, maintainable UIs following modern UI/UX practices.",
      tags: ["Angular", "TypeScript", "UI/UX", "API Integration"],
    },
    {
      company: "ITI",
      title: "Back-End .NET Development",
      period: "January 2025",
      hours: "60 hours",
      description:
        "Advanced C# and ASP.NET Core MVC. Built real-world back-end applications emphasizing clean architecture and dependency injection.",
      tags: ["C#", "ASP.NET Core", "MVC", "Clean Architecture"],
    },
    {
      company: "Cisco DEPI",
      title: "Cybersecurity Training",
      period: "2024",
      hours: "159 hours",
      description:
        "Three semesters covering CCNA fundamentals and Cyber Ops — threat analysis, network security, and incident response in simulated environments.",
      tags: ["CCNA", "Network Security", "Threat Analysis", "Incident Response"],
    },
  ],
} as const;
